/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaServicesRouteImport } from './routes/visa-services'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as TravelInsuranceRouteImport } from './routes/travel-insurance'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ProfileAssessmentRouteImport } from './routes/profile-assessment'
import { Route as PassportServicesRouteImport } from './routes/passport-services'
import { Route as PakistanVisaRouteImport } from './routes/pakistan-visa'
import { Route as HotelBookingRouteImport } from './routes/hotel-booking'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AirTicketingRouteImport } from './routes/air-ticketing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as CountriesSouthernAfricaCountryRouteImport } from './routes/countries.southern-africa.$country'
import { Route as CountriesSouthAsiaCountryRouteImport } from './routes/countries.south-asia.$country'
import { Route as CountriesSouthAmericaCountryRouteImport } from './routes/countries.south-america.$country'
import { Route as CountriesSchengenCountryRouteImport } from './routes/countries.schengen.$country'
import { Route as CountriesOceaniaCountryRouteImport } from './routes/countries.oceania.$country'
import { Route as CountriesNorthAfricaCountryRouteImport } from './routes/countries.north-africa.$country'
import { Route as CountriesMiddleEastCountryRouteImport } from './routes/countries.middle-east.$country'
import { Route as CountriesEuropeOthersCountryRouteImport } from './routes/countries.europe-others.$country'
import { Route as CountriesEastAsiaCountryRouteImport } from './routes/countries.east-asia.$country'
import { Route as CountriesCentralAsiaCountryRouteImport } from './routes/countries.central-asia.$country'
import { Route as CountriesAmericasCountryRouteImport } from './routes/countries.americas.$country'
import { Route as CountriesSlugVisaVisaTypeRouteImport } from './routes/countries.$slug_.visa.$visaType'

const VisaServicesRoute = VisaServicesRouteImport.update({
  id: '/visa-services',
  path: '/visa-services',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelInsuranceRoute = TravelInsuranceRouteImport.update({
  id: '/travel-insurance',
  path: '/travel-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAssessmentRoute = ProfileAssessmentRouteImport.update({
  id: '/profile-assessment',
  path: '/profile-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportServicesRoute = PassportServicesRouteImport.update({
  id: '/passport-services',
  path: '/passport-services',
  getParentRoute: () => rootRouteImport,
} as any)
const PakistanVisaRoute = PakistanVisaRouteImport.update({
  id: '/pakistan-visa',
  path: '/pakistan-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelBookingRoute = HotelBookingRouteImport.update({
  id: '/hotel-booking',
  path: '/hotel-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AirTicketingRoute = AirTicketingRouteImport.update({
  id: '/air-ticketing',
  path: '/air-ticketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/countries/$slug',
  path: '/countries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesSouthernAfricaCountryRoute =
  CountriesSouthernAfricaCountryRouteImport.update({
    id: '/countries/southern-africa/$country',
    path: '/countries/southern-africa/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSouthAsiaCountryRoute =
  CountriesSouthAsiaCountryRouteImport.update({
    id: '/countries/south-asia/$country',
    path: '/countries/south-asia/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSouthAmericaCountryRoute =
  CountriesSouthAmericaCountryRouteImport.update({
    id: '/countries/south-america/$country',
    path: '/countries/south-america/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSchengenCountryRoute =
  CountriesSchengenCountryRouteImport.update({
    id: '/countries/schengen/$country',
    path: '/countries/schengen/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesOceaniaCountryRoute = CountriesOceaniaCountryRouteImport.update({
  id: '/countries/oceania/$country',
  path: '/countries/oceania/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesNorthAfricaCountryRoute =
  CountriesNorthAfricaCountryRouteImport.update({
    id: '/countries/north-africa/$country',
    path: '/countries/north-africa/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesMiddleEastCountryRoute =
  CountriesMiddleEastCountryRouteImport.update({
    id: '/countries/middle-east/$country',
    path: '/countries/middle-east/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesEuropeOthersCountryRoute =
  CountriesEuropeOthersCountryRouteImport.update({
    id: '/countries/europe-others/$country',
    path: '/countries/europe-others/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesEastAsiaCountryRoute =
  CountriesEastAsiaCountryRouteImport.update({
    id: '/countries/east-asia/$country',
    path: '/countries/east-asia/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesCentralAsiaCountryRoute =
  CountriesCentralAsiaCountryRouteImport.update({
    id: '/countries/central-asia/$country',
    path: '/countries/central-asia/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesAmericasCountryRoute =
  CountriesAmericasCountryRouteImport.update({
    id: '/countries/americas/$country',
    path: '/countries/americas/$country',
    getParentRoute: () => rootRouteImport,
  } as any)
const CountriesSlugVisaVisaTypeRoute =
  CountriesSlugVisaVisaTypeRouteImport.update({
    id: '/countries/$slug_/visa/$visaType',
    path: '/countries/$slug/visa/$visaType',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/pakistan-visa': typeof PakistanVisaRoute
  '/passport-services': typeof PassportServicesRoute
  '/profile-assessment': typeof ProfileAssessmentRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/umrah': typeof UmrahRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/countries/americas/$country': typeof CountriesAmericasCountryRoute
  '/countries/central-asia/$country': typeof CountriesCentralAsiaCountryRoute
  '/countries/east-asia/$country': typeof CountriesEastAsiaCountryRoute
  '/countries/europe-others/$country': typeof CountriesEuropeOthersCountryRoute
  '/countries/middle-east/$country': typeof CountriesMiddleEastCountryRoute
  '/countries/north-africa/$country': typeof CountriesNorthAfricaCountryRoute
  '/countries/oceania/$country': typeof CountriesOceaniaCountryRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
  '/countries/south-america/$country': typeof CountriesSouthAmericaCountryRoute
  '/countries/south-asia/$country': typeof CountriesSouthAsiaCountryRoute
  '/countries/southern-africa/$country': typeof CountriesSouthernAfricaCountryRoute
  '/countries/$slug/visa/$visaType': typeof CountriesSlugVisaVisaTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/pakistan-visa': typeof PakistanVisaRoute
  '/passport-services': typeof PassportServicesRoute
  '/profile-assessment': typeof ProfileAssessmentRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/umrah': typeof UmrahRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries': typeof CountriesIndexRoute
  '/countries/americas/$country': typeof CountriesAmericasCountryRoute
  '/countries/central-asia/$country': typeof CountriesCentralAsiaCountryRoute
  '/countries/east-asia/$country': typeof CountriesEastAsiaCountryRoute
  '/countries/europe-others/$country': typeof CountriesEuropeOthersCountryRoute
  '/countries/middle-east/$country': typeof CountriesMiddleEastCountryRoute
  '/countries/north-africa/$country': typeof CountriesNorthAfricaCountryRoute
  '/countries/oceania/$country': typeof CountriesOceaniaCountryRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
  '/countries/south-america/$country': typeof CountriesSouthAmericaCountryRoute
  '/countries/south-asia/$country': typeof CountriesSouthAsiaCountryRoute
  '/countries/southern-africa/$country': typeof CountriesSouthernAfricaCountryRoute
  '/countries/$slug/visa/$visaType': typeof CountriesSlugVisaVisaTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/hotel-booking': typeof HotelBookingRoute
  '/pakistan-visa': typeof PakistanVisaRoute
  '/passport-services': typeof PassportServicesRoute
  '/profile-assessment': typeof ProfileAssessmentRoute
  '/testimonials': typeof TestimonialsRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/umrah': typeof UmrahRoute
  '/visa-services': typeof VisaServicesRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/countries/': typeof CountriesIndexRoute
  '/countries/americas/$country': typeof CountriesAmericasCountryRoute
  '/countries/central-asia/$country': typeof CountriesCentralAsiaCountryRoute
  '/countries/east-asia/$country': typeof CountriesEastAsiaCountryRoute
  '/countries/europe-others/$country': typeof CountriesEuropeOthersCountryRoute
  '/countries/middle-east/$country': typeof CountriesMiddleEastCountryRoute
  '/countries/north-africa/$country': typeof CountriesNorthAfricaCountryRoute
  '/countries/oceania/$country': typeof CountriesOceaniaCountryRoute
  '/countries/schengen/$country': typeof CountriesSchengenCountryRoute
  '/countries/south-america/$country': typeof CountriesSouthAmericaCountryRoute
  '/countries/south-asia/$country': typeof CountriesSouthAsiaCountryRoute
  '/countries/southern-africa/$country': typeof CountriesSouthernAfricaCountryRoute
  '/countries/$slug_/visa/$visaType': typeof CountriesSlugVisaVisaTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/pakistan-visa'
    | '/passport-services'
    | '/profile-assessment'
    | '/testimonials'
    | '/travel-insurance'
    | '/umrah'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries/'
    | '/countries/americas/$country'
    | '/countries/central-asia/$country'
    | '/countries/east-asia/$country'
    | '/countries/europe-others/$country'
    | '/countries/middle-east/$country'
    | '/countries/north-africa/$country'
    | '/countries/oceania/$country'
    | '/countries/schengen/$country'
    | '/countries/south-america/$country'
    | '/countries/south-asia/$country'
    | '/countries/southern-africa/$country'
    | '/countries/$slug/visa/$visaType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/pakistan-visa'
    | '/passport-services'
    | '/profile-assessment'
    | '/testimonials'
    | '/travel-insurance'
    | '/umrah'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries'
    | '/countries/americas/$country'
    | '/countries/central-asia/$country'
    | '/countries/east-asia/$country'
    | '/countries/europe-others/$country'
    | '/countries/middle-east/$country'
    | '/countries/north-africa/$country'
    | '/countries/oceania/$country'
    | '/countries/schengen/$country'
    | '/countries/south-america/$country'
    | '/countries/south-asia/$country'
    | '/countries/southern-africa/$country'
    | '/countries/$slug/visa/$visaType'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/hotel-booking'
    | '/pakistan-visa'
    | '/passport-services'
    | '/profile-assessment'
    | '/testimonials'
    | '/travel-insurance'
    | '/umrah'
    | '/visa-services'
    | '/countries/$slug'
    | '/countries/'
    | '/countries/americas/$country'
    | '/countries/central-asia/$country'
    | '/countries/east-asia/$country'
    | '/countries/europe-others/$country'
    | '/countries/middle-east/$country'
    | '/countries/north-africa/$country'
    | '/countries/oceania/$country'
    | '/countries/schengen/$country'
    | '/countries/south-america/$country'
    | '/countries/south-asia/$country'
    | '/countries/southern-africa/$country'
    | '/countries/$slug_/visa/$visaType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirTicketingRoute: typeof AirTicketingRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HotelBookingRoute: typeof HotelBookingRoute
  PakistanVisaRoute: typeof PakistanVisaRoute
  PassportServicesRoute: typeof PassportServicesRoute
  ProfileAssessmentRoute: typeof ProfileAssessmentRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TravelInsuranceRoute: typeof TravelInsuranceRoute
  UmrahRoute: typeof UmrahRoute
  VisaServicesRoute: typeof VisaServicesRoute
  CountriesSlugRoute: typeof CountriesSlugRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  CountriesAmericasCountryRoute: typeof CountriesAmericasCountryRoute
  CountriesCentralAsiaCountryRoute: typeof CountriesCentralAsiaCountryRoute
  CountriesEastAsiaCountryRoute: typeof CountriesEastAsiaCountryRoute
  CountriesEuropeOthersCountryRoute: typeof CountriesEuropeOthersCountryRoute
  CountriesMiddleEastCountryRoute: typeof CountriesMiddleEastCountryRoute
  CountriesNorthAfricaCountryRoute: typeof CountriesNorthAfricaCountryRoute
  CountriesOceaniaCountryRoute: typeof CountriesOceaniaCountryRoute
  CountriesSchengenCountryRoute: typeof CountriesSchengenCountryRoute
  CountriesSouthAmericaCountryRoute: typeof CountriesSouthAmericaCountryRoute
  CountriesSouthAsiaCountryRoute: typeof CountriesSouthAsiaCountryRoute
  CountriesSouthernAfricaCountryRoute: typeof CountriesSouthernAfricaCountryRoute
  CountriesSlugVisaVisaTypeRoute: typeof CountriesSlugVisaVisaTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa-services': {
      id: '/visa-services'
      path: '/visa-services'
      fullPath: '/visa-services'
      preLoaderRoute: typeof VisaServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-insurance': {
      id: '/travel-insurance'
      path: '/travel-insurance'
      fullPath: '/travel-insurance'
      preLoaderRoute: typeof TravelInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-assessment': {
      id: '/profile-assessment'
      path: '/profile-assessment'
      fullPath: '/profile-assessment'
      preLoaderRoute: typeof ProfileAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport-services': {
      id: '/passport-services'
      path: '/passport-services'
      fullPath: '/passport-services'
      preLoaderRoute: typeof PassportServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pakistan-visa': {
      id: '/pakistan-visa'
      path: '/pakistan-visa'
      fullPath: '/pakistan-visa'
      preLoaderRoute: typeof PakistanVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-booking': {
      id: '/hotel-booking'
      path: '/hotel-booking'
      fullPath: '/hotel-booking'
      preLoaderRoute: typeof HotelBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-ticketing': {
      id: '/air-ticketing'
      path: '/air-ticketing'
      fullPath: '/air-ticketing'
      preLoaderRoute: typeof AirTicketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/countries/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/southern-africa/$country': {
      id: '/countries/southern-africa/$country'
      path: '/countries/southern-africa/$country'
      fullPath: '/countries/southern-africa/$country'
      preLoaderRoute: typeof CountriesSouthernAfricaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/south-asia/$country': {
      id: '/countries/south-asia/$country'
      path: '/countries/south-asia/$country'
      fullPath: '/countries/south-asia/$country'
      preLoaderRoute: typeof CountriesSouthAsiaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/south-america/$country': {
      id: '/countries/south-america/$country'
      path: '/countries/south-america/$country'
      fullPath: '/countries/south-america/$country'
      preLoaderRoute: typeof CountriesSouthAmericaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/schengen/$country': {
      id: '/countries/schengen/$country'
      path: '/countries/schengen/$country'
      fullPath: '/countries/schengen/$country'
      preLoaderRoute: typeof CountriesSchengenCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/oceania/$country': {
      id: '/countries/oceania/$country'
      path: '/countries/oceania/$country'
      fullPath: '/countries/oceania/$country'
      preLoaderRoute: typeof CountriesOceaniaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/north-africa/$country': {
      id: '/countries/north-africa/$country'
      path: '/countries/north-africa/$country'
      fullPath: '/countries/north-africa/$country'
      preLoaderRoute: typeof CountriesNorthAfricaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/middle-east/$country': {
      id: '/countries/middle-east/$country'
      path: '/countries/middle-east/$country'
      fullPath: '/countries/middle-east/$country'
      preLoaderRoute: typeof CountriesMiddleEastCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/europe-others/$country': {
      id: '/countries/europe-others/$country'
      path: '/countries/europe-others/$country'
      fullPath: '/countries/europe-others/$country'
      preLoaderRoute: typeof CountriesEuropeOthersCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/east-asia/$country': {
      id: '/countries/east-asia/$country'
      path: '/countries/east-asia/$country'
      fullPath: '/countries/east-asia/$country'
      preLoaderRoute: typeof CountriesEastAsiaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/central-asia/$country': {
      id: '/countries/central-asia/$country'
      path: '/countries/central-asia/$country'
      fullPath: '/countries/central-asia/$country'
      preLoaderRoute: typeof CountriesCentralAsiaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/americas/$country': {
      id: '/countries/americas/$country'
      path: '/countries/americas/$country'
      fullPath: '/countries/americas/$country'
      preLoaderRoute: typeof CountriesAmericasCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$slug_/visa/$visaType': {
      id: '/countries/$slug_/visa/$visaType'
      path: '/countries/$slug/visa/$visaType'
      fullPath: '/countries/$slug/visa/$visaType'
      preLoaderRoute: typeof CountriesSlugVisaVisaTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirTicketingRoute: AirTicketingRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HotelBookingRoute: HotelBookingRoute,
  PakistanVisaRoute: PakistanVisaRoute,
  PassportServicesRoute: PassportServicesRoute,
  ProfileAssessmentRoute: ProfileAssessmentRoute,
  TestimonialsRoute: TestimonialsRoute,
  TravelInsuranceRoute: TravelInsuranceRoute,
  UmrahRoute: UmrahRoute,
  VisaServicesRoute: VisaServicesRoute,
  CountriesSlugRoute: CountriesSlugRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  CountriesAmericasCountryRoute: CountriesAmericasCountryRoute,
  CountriesCentralAsiaCountryRoute: CountriesCentralAsiaCountryRoute,
  CountriesEastAsiaCountryRoute: CountriesEastAsiaCountryRoute,
  CountriesEuropeOthersCountryRoute: CountriesEuropeOthersCountryRoute,
  CountriesMiddleEastCountryRoute: CountriesMiddleEastCountryRoute,
  CountriesNorthAfricaCountryRoute: CountriesNorthAfricaCountryRoute,
  CountriesOceaniaCountryRoute: CountriesOceaniaCountryRoute,
  CountriesSchengenCountryRoute: CountriesSchengenCountryRoute,
  CountriesSouthAmericaCountryRoute: CountriesSouthAmericaCountryRoute,
  CountriesSouthAsiaCountryRoute: CountriesSouthAsiaCountryRoute,
  CountriesSouthernAfricaCountryRoute: CountriesSouthernAfricaCountryRoute,
  CountriesSlugVisaVisaTypeRoute: CountriesSlugVisaVisaTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
